
"""
Django settings for pdtpproject project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'v83zop^u-gt)+b%38$ph%u=i027720y055=r=y6mhh5p3lnna#'

# SECURITY WARNING: don't run with debug turned on in production!

DEBUG = True



ALLOWED_HOSTS = ['127.0.0.1','digitalent.go.ke','www.digitalent.go.ke']

SITE_ID = 1
# Application definition
#SECURE_SSL_REDIRECT = True
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     #additional packages
    #'pdtp',
    'app',
    'deployments',
    'performance',
    
    

    #packages
    'tinymce',
    'auditlog',
    'bootstrap3',
    'phonenumber_field',
    'datetimewidget',
    'dynamic_formsets',
    'bootstrapform',
    'post_office',
    #All Auth Settings
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'django_cleanup',
    'django_unused_media',
    'admin_honeypot',
]

MIDDLEWARE = [
    #'sslify.middleware.SSLifyMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',    
]

ROOT_URLCONF = 'pdtpproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pdtpproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases



# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS=[os.path.join(BASE_DIR,'static')]
STATIC_ROOT=os.path.join(BASE_DIR,'static_files')

MEDIA_URL='/media/'
MEDIA_ROOT=os.path.join(BASE_DIR,'media_files')

#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
ACCOUNT_SIGNUP_FORM_CLASS = 'app.forms.SignupForm'
EMAIL_BACKEND = 'post_office.EmailBackend'

ACCOUNT_EMAIL_REQUIRED=True
LOGIN_REDIRECT_URL='/app/check_password/'
ACCOUNT_AUTHENTICATION_METHOD="email"

ACCOUNT_CONFIRM_EMAIL_ON_GET =False
#ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL=LOGIN_URL
#ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL='/'
#ACCOUNT_EMAIL_CONFIRMATION_EXPIRE_DAYS=2
#EMAIL_CONFIRMATION_SIGNUP = True
ACCOUNT_LOGOUT_REDIRECT_URL='/'
ACCOUNT_SIGNUP_PASSWORD_VERIFICATION=True
ACCOUNT_UNIQUE_EMAIL=True
#ACCOUNT_USERNAME_MIN_LENGTH=3
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_USERNAME_REQUIRED=False
ACCOUNT_PASSWORD_MIN_LENGTH=4
ACCOUNT_LOGOUT_ON_GET= True
#ACCOUNT_EMAIL_VERIFICATION ="mandatory"
#ACCOUNT_USERNAME_REQUIRED = False
#ACCOUNT_SIGNUP_FORM_CLASS = 'UserProfile.forms.SignupForm'
#ACCOUNT_LOGOUT_ON_GET=True

EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587 #TLS or 465 SSL
EMAIL_HOST_USER = 'pdtp@ict.go.ke'
EMAIL_HOST_PASSWORD = 'cohort2@pdtp'
DEFAULT_FROM_EMAIL='pdtp@ict.go.ke'
EMAIL_USE_TLS = True #_USE_SSL


AUTHENTICATION_BACKENDS = (
    # Needed to login by username in Django admin, regardless of `allauth`
    "django.contrib.auth.backends.ModelBackend",
    # `allauth` specific authentication methods, such as login by e-mail
    "allauth.account.auth_backends.AuthenticationBackend"
)
BOOTSTRAP3 = {
    # Set HTML required attribute on required fields
    'set_required': False,
}
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
#TINYMCE_JS_URL = os.path.join(STATIC_ROOT, "js/tiny_mce/tiny_mce.js")
TINYMCE_JS_ROOT = os.path.join(STATIC_ROOT, "js/tiny_mce")
TINYMCE_SPELLCHECKER = True
TINYMCE_COMPRESSOR = True
TINYMCE_DEFAULT_CONFIG = {
    'theme': "simple",
    'plugins': "spellchecker",
    'theme_advanced_buttons3_add': "|,spellchecker",
}
from pdtpproject.local_settings import *   


CELERY_TRACK_STARTED = True
CELERY_BROKER_URL = 'amqp://localhost'
# CELERY_RESULT_BACKEND = 'amqp://localhost'
CELERY_RESULT_BACKEND = 'rpc'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'

CELERY_TIMEZONE = 'UTC'
CELERY_ENABLE_UTC = True
