# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-26 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlummniDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Phone Number')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=200, null=True)),
                ('employer', models.CharField(max_length=400, verbose_name='Current Employer')),
                ('job', models.CharField(max_length=400, verbose_name='Current Job')),
                ('country', models.CharField(max_length=400, verbose_name=' In what country do you currently live?')),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PdtpYear')),
                ('speciality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Specialization')),
            ],
        ),
    ]
