# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-26 11:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alummnidatabase'),
    ]

    operations = [
        migrations.AddField(
            model_name='alummnidatabase',
            name='date_registered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
