# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-27 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alummnidatabase_date_registered'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('pdtp_contacted', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='alummnidatabase',
            name='country',
            field=models.CharField(max_length=400, verbose_name=' In which country do you currently live?'),
        ),
        migrations.AlterField(
            model_name='alummnidatabase',
            name='job',
            field=models.CharField(max_length=400, verbose_name='Current Job(Position)'),
        ),
        migrations.AlterField(
            model_name='alummnidatabase',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Full Name'),
        ),
    ]
