# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-05 12:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pdtpproject.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance', '0002_auto_20190405_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('report', models.FileField(blank=True, help_text='only pdf files allowed', null=True, upload_to='mentorship reports', validators=[pdtpproject.validators.validate_file_extension], verbose_name='Attach Reports(max 4 Files)')),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_approved_by_mentor', to=settings.AUTH_USER_MODEL)),
                ('pdtp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
