# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-05 12:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0003_mentorshipreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorshipreport',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_approved_by_mentor', to=settings.AUTH_USER_MODEL),
        ),
    ]
