# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-10 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0005_auto_20190405_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='innovationevaluation',
            name='final',
            field=models.IntegerField(default=0, verbose_name='Final Evaluation'),
        ),
        migrations.AlterField(
            model_name='innovationevaluation',
            name='evaluation',
            field=models.IntegerField(default=0, verbose_name='First Evaluation'),
        ),
        migrations.AlterField(
            model_name='innovationevaluation',
            name='initiative',
            field=models.IntegerField(default=0, verbose_name='Submission/Initiative'),
        ),
        migrations.AlterField(
            model_name='innovationevaluation',
            name='presentation',
            field=models.IntegerField(default=0, verbose_name='Shortlisted'),
        ),
    ]
