# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-10 09:08
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0006_auto_20190410_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='innovationevaluation',
            name='evaluation',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)], verbose_name='First Evaluation'),
        ),
        migrations.AlterField(
            model_name='innovationevaluation',
            name='initiative',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='Submission/Initiative'),
        ),
        migrations.AlterField(
            model_name='innovationevaluation',
            name='presentation',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(0)], verbose_name='Shortlisted'),
        ),
        migrations.AlterField(
            model_name='innovationevaluation',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
