# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-10 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0008_supervisortoevaluate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buddyapprovalcomment',
            name='comment',
            field=models.CharField(max_length=500, verbose_name='Kindly share your overall assesment of the intern (a paragraph not a single word)'),
        ),
        migrations.AlterField(
            model_name='buddycomment',
            name='comment',
            field=models.CharField(max_length=500, verbose_name='Kindly share your overall assesment of the intern (a paragraph not a single word)'),
        ),
        migrations.AlterField(
            model_name='mentorcomment',
            name='comment',
            field=models.CharField(max_length=500, verbose_name='Kindly share your overall assesment of the intern (a paragraph not a single word)'),
        ),
        migrations.AlterField(
            model_name='supervisorapprovalcomment',
            name='comment',
            field=models.CharField(max_length=500, verbose_name='Kindly share your overall assesment of the intern (a paragraph not a single word)'),
        ),
    ]
