# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-10 17:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0010_auto_20190410_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisorapprovalcomment',
            name='award_marks',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)], verbose_name='Award the intern marks as per his/her performance in your ourgnization and based on the report above'),
        ),
    ]
