# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-13 08:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('performance', '0013_auto_20190410_2126'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorshipInternReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awareness_description', models.CharField(max_length=300)),
                ('awareness_impact', models.CharField(max_length=300)),
                ('goal_description', models.CharField(max_length=300)),
                ('goal_impact', models.CharField(max_length=300)),
                ('adaptability_description', models.CharField(max_length=300)),
                ('adaptability_impact', models.CharField(max_length=300)),
                ('confidence_description', models.CharField(max_length=300)),
                ('confidence_impact', models.CharField(max_length=300)),
                ('presentation_description', models.CharField(max_length=300)),
                ('presentation_impact', models.CharField(max_length=300)),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_mentor', to=settings.AUTH_USER_MODEL)),
                ('pdtp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
