# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-23 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0014_mentorshipinternreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort', models.CharField(max_length=200)),
            ],
        ),
    ]
