# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-23 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0015_cohort'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivation', models.CharField(max_length=200, verbose_name='What motivated you to join the PDTP Programme? *(200 characters')),
                ('other', models.CharField(blank=True, max_length=500, null=True)),
                ('reason', models.CharField(blank=True, max_length=200, null=True, verbose_name="If you didn't stay for 12 Months period, what was your reason(s)")),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.Cohort', verbose_name='Which of the following represents your cohort?')),
            ],
        ),
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='basicevaluation',
            name='completion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performance.Complete', verbose_name='Did you complete the 12-months internship period? After how long did you exit?'),
        ),
        migrations.AddField(
            model_name='basicevaluation',
            name='education',
            field=models.ManyToManyField(to='performance.Level', verbose_name='If in school, which level of education?'),
        ),
        migrations.AddField(
            model_name='basicevaluation',
            name='work',
            field=models.ManyToManyField(to='performance.Work', verbose_name='What are you currently doing? *'),
        ),
    ]
