# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-03 14:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_attended', models.IntegerField(verbose_name='Days Attended')),
                ('date_submitted', models.DateTimeField(auto_now_add=True, null=True)),
                ('pdtp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_attendance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Attendance',
            },
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(max_length=200)),
                ('confirmed', models.BooleanField(default=True)),
                ('date_confirmed', models.DateField(auto_now_add=True)),
                ('reporting_date', models.DateField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('reporting_details', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Attachment Reporting Instructions:')),
                ('interview', models.BooleanField(default=False)),
                ('date_invited', models.DateField(blank=True, null=True)),
                ('interview_date', models.DateField(blank=True, null=True)),
                ('interview_instructions', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Interview Instructions:')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InternMEParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Intern M & E parameter')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PdtpYear')),
            ],
        ),
        migrations.CreateModel(
            name='InternMERate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=500)),
                ('intern_parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.InternMEParameter', verbose_name='Intern parameter')),
                ('pdtp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InternSupervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringAndEvaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cohort Year')),
                ('projects', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Projects involved in at the Ministry/State Corporation/County')),
                ('my_contribution', tinymce.models.HTMLField(blank=True, null=True, verbose_name='My Contribution to those projects')),
                ('lessons_learned_during_internship', tinymce.models.HTMLField(null=True, verbose_name='Briefly describe what you consider to be your most significant lessons learned so far during this internship?Please provide specific examples.')),
                ('specific_projects_or_assignments_you_are_given', tinymce.models.HTMLField(null=True, verbose_name='What specific projects or assignments are you givenduring the internship?')),
                ('projects_given_are_they_challenging_or_stimulating', tinymce.models.HTMLField(null=True, verbose_name='specific projects or assignments given ,Are they challenging and stimulating?')),
                ('evaluate_your_experience', tinymce.models.HTMLField(null=True, verbose_name='Please evaluate your experience with each one of the projects and assigements you listed above')),
                ('instruction_and_Directions_given_by_supervisor', tinymce.models.HTMLField(null=True, verbose_name='Are you given adequate instruction anddirection/support from staff/supervisor in order to complete your assignments?')),
                ('supervisor_availability', models.CharField(max_length=100, null=True, verbose_name='Has your supervisor been available and accessible tosupport you whenever you needed?')),
                ('field_of_specialization', tinymce.models.HTMLField(null=True, verbose_name='Has this internship stimulated your interest in your fieldof Specialization (Application, Networking, Security orProject Management)? Why or why not?')),
                ('opportunities_for_learning', models.CharField(max_length=1000, null=True, verbose_name='Are there ample opportunities for learning?')),
                ('preparedness_to_enter_world_of_work', models.CharField(max_length=500, null=True, verbose_name='Do you feel that you are better prepared to enter theworld of work/innovation after the internship?')),
                ('Your_relationship_with_other_workers', models.CharField(max_length=1000, null=True, verbose_name='How’s your working relationship with the other workersin the organization?')),
                ('How_have_you_been_treated_by_the_organization', models.CharField(max_length=1000, null=True)),
                ('Has_the_attachment_met_your_expectations', models.CharField(max_length=1000, null=True, verbose_name='Has the attachment met your expectations as per thePDTP curriculum (time, office environment, type of work)? Please explain.')),
                ('suggestions_to_improve_the_internship_programme', tinymce.models.HTMLField(null=True, verbose_name='Based on your experience, what suggestions can youprovide which can improve the program in regards to internships/attachments in private/public sector in thefuture?')),
                ('recommend_this_organisation', tinymce.models.HTMLField(null=True, verbose_name='Would you recommend this organisation for internship to others? Why/why not?')),
                ('best_practices', tinymce.models.HTMLField(null=True, verbose_name='What best practices can we apply to the government from the private sector? (For Private sector internships ONLY)')),
                ('innovation', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Have you identified any innovation opportunities at your place of attachment? if yes list them')),
                ('innovation_reason', tinymce.models.HTMLField(null=True, verbose_name='Have you identified any innovation opportunities at your place of attachment? if No Give reasons')),
                ('mentorship_sessions', models.CharField(max_length=100, null=True, verbose_name='How many times have u met your mentor?')),
                ('mentorship_lesson_learned', tinymce.models.HTMLField(blank=True, null=True, verbose_name='State lessons (if any) learnt from your mentor:')),
                ('mentorship_problem_faced', tinymce.models.HTMLField(blank=True, null=True, verbose_name='State any problem relating to mentorship')),
                ('training_attended', tinymce.models.HTMLField(null=True, verbose_name='How many Trainings have you attended? List them')),
                ('Certifications_attained', tinymce.models.HTMLField(null=True, verbose_name='How many Certifications have you successfully done? List them')),
                ('suggestion_on_job_training', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Your Suggestions On-job training at attachment station')),
                ('suggestion_innovation', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Your Suggestions on Innovations')),
                ('suggestion_mentorship', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Your Suggestions on Mentorship')),
                ('suggestion_training', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Your Suggestions on Training and Certifications')),
                ('comment_icta_secretariat_support', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Your Comment on the support given to you by the ICT Authority/PDTP Secretariat')),
                ('challenges_faced', models.CharField(blank=True, max_length=1000, null=True, verbose_name='List any challenges you have faced during your time in the programme:')),
                ('date_supervisor_submitted', models.DateField(blank=True, null=True)),
                ('date_submitted_by_intern', models.DateField(auto_now_add=True)),
                ('intern_strength', tinymce.models.HTMLField(blank=True, null=True, verbose_name='What are the interns outstanding STRENGTHS')),
                ('areas_improvement', tinymce.models.HTMLField(blank=True, null=True, verbose_name='In what areas does the intern need IMPROVEMENT?')),
                ('pdtp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringAndEvaluationPhase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(max_length=200, unique=True)),
                ('secretariat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phase', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MonitoringStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'MonitoringStatus',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.BooleanField(choices=[(True, 'Public'), (False, 'Private')], default=False)),
                ('organization', models.CharField(max_length=255, unique=True, verbose_name='Organization Name')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='Physical Location')),
                ('town', models.CharField(blank=True, max_length=200, null=True, verbose_name='Town Located')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='Companie Logos')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.County', verbose_name='County Located')),
            ],
            options={
                'verbose_name_plural': 'Partner Organizations and MDAs',
            },
        ),
        migrations.CreateModel(
            name='Parametor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='PhaseOrQuarter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quater', models.CharField(max_length=200, unique=True)),
                ('secretariat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phase_quaters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='QuarterlyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('date_approved', models.DateTimeField(auto_now_add=True, null=True)),
                ('introduction', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Summary of Your Experience in place of Deployment')),
                ('projects_involved', tinymce.models.HTMLField(blank=True, help_text='Name and description of the project', null=True, verbose_name='Projects Involved in at place of Deployment ')),
                ('innovation_opportunity', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Innovations opportunities at Deployment Station')),
                ('mentorship_progress', tinymce.models.HTMLField(blank=True, null=True)),
                ('training_certification', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Training and certifications done so far/in progress')),
                ('lesson_learnt', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Lesson Learnt from Your deployment station')),
                ('challenges_faced', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Challenges Experienced while Undertaking your duties')),
                ('recommendation', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Recommendations to Improve PDTP programme')),
                ('comments', tinymce.models.HTMLField(blank=True, max_length=500, null=True, verbose_name='Supervisor Comments')),
                ('pdtp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('project_Category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.ProjectSection')),
                ('quater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.PhaseOrQuarter')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='station_supervisor', to=settings.AUTH_USER_MODEL)),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PdtpYear')),
            ],
        ),
        migrations.CreateModel(
            name='ReportStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'ReportStatus',
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(blank=True, max_length=200, null=True, verbose_name='Business Title')),
                ('is_contact_person', models.BooleanField(default=False)),
                ('honors', models.CharField(blank=True, max_length=200, null=True, verbose_name='Honors')),
                ('mentor_availability', models.BooleanField(default=True, verbose_name='Availability')),
                ('is_mentor', models.BooleanField(default=False, verbose_name='Is a Mentor')),
                ('is_supervisor', models.BooleanField(default=False, verbose_name='Is a Supervisor')),
                ('is_buddy', models.BooleanField(default=False, verbose_name='Is a Buddy')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.Organization')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mentors and Supervisors',
            },
        ),
        migrations.CreateModel(
            name='SupervisorMEParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='supervisor M & E parameter')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PdtpYear')),
            ],
        ),
        migrations.CreateModel(
            name='SupervisorMERate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Jibu', models.CharField(blank=True, max_length=100, null=True)),
                ('pdtp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intern_supervisor_rates', to=settings.AUTH_USER_MODEL)),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.MonitoringAndEvaluationPhase')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supervisor_parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.SupervisorMEParameter', verbose_name='Supervisor parameter')),
            ],
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name=' Title')),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(help_text='e.g. PDTP Helpdesk system(Indicate whether new or existing)max 100 words', max_length=100, verbose_name='Assignment/Project Name')),
                ('task', models.CharField(help_text='e.g.Collection and compiling of user requirements, Design, Testing, Implementation (max 300 words)', max_length=300, verbose_name='Activity/Task')),
                ('resources', models.CharField(help_text='e.g. Laptops, finances (max 300 words)', max_length=300, verbose_name='Input/Resources required')),
                ('outputs', models.CharField(help_text='e.g. PDTP Helpdesk system(Max 300 Words ', max_length=300, verbose_name='Outputs/Deliverables(Measurable)')),
                ('expected_impact', models.CharField(help_text='Max 300 words', max_length=300)),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
                ('status', models.CharField(help_text='Max 300 words', max_length=300)),
                ('approved_by_supervisor', models.BooleanField(default=False, verbose_name='Approve?')),
                ('supervisor_comment', models.CharField(blank=True, max_length=300, null=True, verbose_name='Comment')),
                ('date_approved', models.DateField(blank=True, null=True)),
                ('date_submitted', models.DateField(auto_now_add=True)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.Organization')),
                ('pdtp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='intern_supervisor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_submitted', 'pdtp'],
            },
        ),
        migrations.AddField(
            model_name='supervisor',
            name='title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.Title', verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='phaseorquarter',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.ReportStatus'),
        ),
        migrations.AddField(
            model_name='monitoringandevaluationphase',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.MonitoringStatus'),
        ),
        migrations.AddField(
            model_name='monitoringandevaluationphase',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.PdtpYear'),
        ),
        migrations.AddField(
            model_name='monitoringandevaluation',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.MonitoringAndEvaluationPhase', verbose_name='Monitoring and Evaluation Phase'),
        ),
        migrations.AddField(
            model_name='monitoringandevaluation',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Intern_report', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internsupervisor',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.Organization'),
        ),
        migrations.AddField(
            model_name='internsupervisor',
            name='pdtp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internsupervisor',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sup_assigned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='internmerate',
            name='phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deployments.MonitoringAndEvaluationPhase'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='parameter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.Parametor'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='pdtp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdtp', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='supervisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deployment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deployments.Organization'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='pdtp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deployment',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PdtpYear'),
        ),
    ]
